Hw1ver1
sharkovadarya/java2017fall pull request #1
Opened 2017-09-11 20:24 UTC by sharkovadarya

Pull request from a separate branch to the master branch, as the task statement requires.

2017-09-16 06:54 UTC, jzuken requested changes

2017-09-16 06:54 UTC, jzuken commented on hw1/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
этот файл тут вряд ли нужен, у нас же нет никакого графического интерфейса

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/HashTable.java
> +    private static int tableSize;
а почему оно статик? если я две хэш-таблицы создам, у них должен быть одинаковый размер?

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/HashTable.java
> +        tableSizesIndex = 0;
инициализацию лучше совмещать с объявлением полей

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/HashTable.java
> +     * This method inserts a new hash table entry to the table.
а тут ничего не написано про то, что старое значение стирается

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/HashTableEntry.java
> +public class HashTableEntry {
по сути это класс Pair, лучше его так и назвать

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/Node.java
> +public class Node {
а зачем вам два класса Node? второй у вас внутри списка объявлен, где ему и место

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/HashTable.java
> +package ru.spbau.group202.sharkova;
давайте сделаем отдельный пакет для хэш-таблицы

2017-09-16 06:54 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/Main.java
> +        if (length < 1) throw new IllegalArgumentException();
это, конечно, вкусовщина, но мне кажется, что лучше всё же писать на разных строках такие конструкции. просто глазу проще будет структуру кода определять

2017-09-17 16:27 UTC, sharkovadarya commented
>а тут ничего не написано про то, что старое значение стирается
Я не очень понимаю, что имеется в виду; можно, пожалуйста, подробнее
объяснить, что не так?

Заранее спасибо.

2017-09-16 9:54 GMT+03:00 Timofey Bryksin <notifications@github.com>:

> *@jzuken* requested changes on this pull request.
> ------------------------------
>
> In hw1/.idea/uiDesigner.xml
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139279994>
> :
>
> > @@ -0,0 +1,124 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> этот файл тут вряд ли нужен, у нас же нет никакого графического интерфейса
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/HashTable.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280079>
> :
>
> > +
> +    /* The table has a maximal acceptable size,
> +     * after achieving which the table will be resized.
> +     * The maximal size (maxSize variable) is calculated
> +     * as (THRESHOLD) per cent of tableSize
> +     */
> +    private final static double THRESHOLD = 0.75;
> +    /* good hash table sizes
> +     * source: http://www.orcca.on.ca/~yxie/courses/cs2210b-2011/htmls/extra/PlanetMath_%20goodhashtable.pdf */
> +    private final static int goodTableSizes[] = {53, 97, 193, 389, 769,
> +                                                1543, 3079, 6151,
> +                                                12289, 24593, 49157,
> +                                                98317, 196613, 393241,
> +                                                786433, 1572869, 3145739,
> +                                                6291469};
> +    private static int tableSize;
>
> а почему оно статик? если я две хэш-таблицы создам, у них должен быть
> одинаковый размер?
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/HashTable.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280093>
> :
>
> > +    /**
> +     * @param string string the hash value of which will be found.
> +     * @return hash value of the given string fit for the table.
> +     */
> +    private int getHashValue(String string) {
> +        return (string.hashCode() & 0x7fffffff) % tableSize;
> +    }
> +
> +    /**
> +     * Empty hash table constructor.
> +     * Each cell is initialized
> +     * as an empty singly-linked list of hash table entries.
> +     */
> +    public HashTable() {
> +        tableSize = goodTableSizes[0]; // default hash table size
> +        tableSizesIndex = 0;
>
> инициализацию лучше совмещать с объявлением полей
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/HashTable.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280133>
> :
>
> > +        for (SinglyLinkedList list : oldHashTable) {
> +            if (list.getSize() != 0) {
> +                int index = 0;
> +                HashTableEntry entry = list.getByIndex(index);
> +                while (entry != null) {
> +                    /* Since rehashing takes place,
> +                     * we need to put all entries in again */
> +                    put(entry.getKey(), entry.getValue());
> +                    entry = list.getByIndex(++index);
> +                }
> +            }
> +        }
> +    }
> +
> +    /**
> +     * This method inserts a new hash table entry to the table.
>
> а тут ничего не написано про то, что старое значение стирается
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/HashTableEntry.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280155>
> :
>
> > @@ -0,0 +1,29 @@
> +package ru.spbau.group202.sharkova;
> +
> +/**
> + * This class represents a hash table entry.
> + * An entry consists of a key and a value.
> + */
> +public class HashTableEntry {
>
> по сути это класс Pair, лучше его так и назвать
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/Node.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280176>
> :
>
> > @@ -0,0 +1,56 @@
> +package ru.spbau.group202.sharkova;
> +
> +/** This class represents a linked list node;
> + * stores given data; can go to the next node in the list.
> + */
> +public class Node {
>
> а зачем вам два класса Node? второй у вас внутри списка объявлен, где ему
> и место
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/HashTable.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280181>
> :
>
> > @@ -0,0 +1,177 @@
> +package ru.spbau.group202.sharkova;
>
> давайте сделаем отдельный пакет для хэш-таблицы
> ------------------------------
>
> In hw1/src/ru/spbau/group202/sharkova/Main.java
> <https://github.com/sharkovadarya/java2017fall/pull/1#discussion_r139280204>
> :
>
> > +    public static final String upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
> +
> +    public static final String lower = upper.toLowerCase(Locale.ROOT);
> +
> +    public static final String digits = "0123456789";
> +
> +    public static final String alphanum = upper + lower + digits;
> +
> +    private final Random random;
> +
> +    private final char[] symbols;
> +
> +    private final char[] buf;
> +
> +    public RandomString(int length, Random random, String symbols) {
> +        if (length < 1) throw new IllegalArgumentException();
>
> это, конечно, вкусовщина, но мне кажется, что лучше всё же писать на
> разных строках такие конструкции. просто глазу проще будет структуру кода
> определять
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sharkovadarya/java2017fall/pull/1#pullrequestreview-63196625>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMHoAb0zx_1JBKjhLtHMyZd7ScvtEFhlks5si3C8gaJpZM4PTuHu>
> .
>

2017-09-23 11:58 UTC, jzuken commented on hw1/src/ru/spbau/group202/sharkova/hw1/SinglyLinkedList.java
> +        head = null;
это лучше совмещать с определением полей

2017-09-23 11:58 UTC, merged