Hash Table Tests
sharkovadarya/java2017fall pull request #3
Opened 2017-09-24 12:36 UTC by sharkovadarya

2017-09-25 06:21 UTC, jzuken requested changes

2017-09-25 06:21 UTC, jzuken commented on hw1/.idea/libraries/Arquillian_JUnit_Release.xml
> +    <properties maven-id="org.jboss.arquillian.junit:arquillian-junit-container:RELEASE" />
эээ, это не тот junit. правильный вот этот: https://mvnrepository.com/artifact/junit/junit

2017-09-25 06:21 UTC, jzuken commented on hw1/test/ru/spbau/group202/sharkova/hw1/HashTableTest.java
> +public class HashTableTest {
хочется ещё тест на разрешение коллизий

2017-09-25 19:01 UTC, sharkovadarya commented on hw1/test/ru/spbau/group202/sharkova/hw1/HashTableTest.java
> +public class HashTableTest {
Что должно быть в этом тесте? Мне казалось, у меня уже есть тесты, которые это и делают: это testPutEqualHashElements(), testGetEqualHashElements(), testRemoveEqualHashElements(). Не хватает теста для contains(), я добавлю, но, наверное, имелось в виду что-то другое?

2017-10-04 12:05 UTC, jzuken requested changes

2017-10-04 12:05 UTC, jzuken commented on hw2/src/main/java/ru/spbau/group202/sharkova/hw2/SpiralMatrix.java
> +package ru.spbau.group202.sharkova.hw2;
а задача про спираль зачем тут? оно вон и пуллреквест не даёт замерджить из-за конфликтов. поправьте, пожалуйста

2017-10-04 15:21 UTC, closed without merging