hw5: set
sharkovadarya/java2017fall pull request #9
Opened 2017-10-17 13:41 UTC by sharkovadarya

2017-10-23 10:11 UTC, jzuken requested changes

2017-10-23 10:11 UTC, jzuken commented on hw5set/src/test/java/ru/spbau/group202/sharkova/hw5set/SetTest.java
> +            assertEquals(true, setString.add(null));
ну вообще оно и не должно какое-то другое исключение кидать, это же статический анализатор. оно подчеркнёт жёлтым и скажет, что что-то не то передаётся:
![image](https://user-images.githubusercontent.com/705678/31883682-552060c2-b7f3-11e7-9142-16ce294cd12d.png)

2017-10-23 10:11 UTC, jzuken commented on hw5set/src/main/java/ru/spbau/group202/sharkova/hw5set/Set.java
> +    @SuppressWarnings("unchecked")
а вот это тут совсем не оправданно. compareTo() подсвечивается, потому что при описании класса вместо T extends Comparable надо было написать T extends Comparable<T>

2017-11-06 17:46 UTC, sharkovadarya commented on hw5set/src/test/java/ru/spbau/group202/sharkova/hw5set/SetTest.java
> +            assertEquals(true, setString.add(null));
Да, я заметила, что в IDEA так и будет. Но если запускать тесты из консоли при помощи mvn tests, будет брошено NPE. Я убрала эту проверку, но теперь при запуске из консоли один тест не проходит.

2017-11-18 10:44 UTC, merged